services:
  db:
    image: mysql:8.0
    hostname: ${DB_HOST}
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysqldata:
